#DATABASE USED = Postgres
#EXECUTOR USED = Celery
#CELERY RESULT BACKEND = Postgres
#CELERY BROKER URL = Redis (redis://:password@hostname:port/db_number)
#AUTH BACKEND = Basic Auth

#PLEASE CHECK README BEFORE EXECUTING THIS FILE ***

---
version: '3'
x-airflow-common-conf:
  &airflow-common-conf
  image: apache/airflow:2.0.2
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://<user>:<password>@<host>/<db>
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://<user>:<password>@<host>/<db>
    AIRFLOW__CELERY__BROKER_URL: redis://<:password>@<hostname>:<port>/<db_number>
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Asia/Kolkata'
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: 'Asia/Kolkata'
    AIRFLOW__WEBSERVER__WORKERS: 1
    AIRFLOW__WEBSERVER__ACCESS_LOGFILE: '/opt/airflow/logs/access.log'
    AIRFLOW__WEBSERVER__ERROR_LOGFILE: '/opt/airflow/logs/error.log'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    AIRFLOW__WEBSERVER__EXPOSE_HOSTNAME: 'true'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins

services:
  airflow-webserver:
    <<: *airflow-common-conf
    command: webserver
    ports:
      - 8080:8080
    restart: always
    depends_on:
        airflow-init:
            condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common-conf
    command: scheduler
    restart: always
    depends_on:
        airflow-init:
            condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-common-conf
    command: celery worker
    restart: always
    depends_on:
        airflow-init:
            condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common-conf
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: 'airflow'
      _AIRFLOW_WWW_USER_PASSWORD: 'airflow'

